# Generated by Django 5.0.6 on 2024-06-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='desc',
            field=models.CharField(db_column='desc', max_length=300),
        ),
        migrations.RenameField(
            model_name='book',
            old_name='desc',
            new_name='author',
        ),
    ]
